// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"
	"database/sql"
)

const listAuditLogsByOperator = `-- name: ListAuditLogsByOperator :many
SELECT id, operator_id, player_id, action, details, created_at
FROM audit_logs
WHERE operator_id = $1
ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
`

type ListAuditLogsByOperatorParams struct {
	OperatorID int32 `json:"operator_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListAuditLogsByOperator(ctx context.Context, arg ListAuditLogsByOperatorParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByOperator, arg.OperatorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.PlayerID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByOperatorPlayer = `-- name: ListAuditLogsByOperatorPlayer :many
SELECT id, operator_id, player_id, action, details, created_at
FROM audit_logs
WHERE operator_id = $1
  AND player_id = $2
ORDER BY created_at DESC
    LIMIT $3 OFFSET $4
`

type ListAuditLogsByOperatorPlayerParams struct {
	OperatorID int32         `json:"operator_id"`
	PlayerID   sql.NullInt32 `json:"player_id"`
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
}

func (q *Queries) ListAuditLogsByOperatorPlayer(ctx context.Context, arg ListAuditLogsByOperatorPlayerParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByOperatorPlayer,
		arg.OperatorID,
		arg.PlayerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.PlayerID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
