// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bets.sql

package sqlc

import (
	"context"
)

const createBet = `-- name: CreateBet :one
INSERT INTO bets (
    operator_id, player_id, round_id,
    amount, outcome, win_amount,
    status, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    RETURNING id, operator_id, player_id, round_id, amount, outcome, win_amount, status, idempotency_key, created_at
`

type CreateBetParams struct {
	OperatorID     int32   `json:"operator_id"`
	PlayerID       int32   `json:"player_id"`
	RoundID        int32   `json:"round_id"`
	Amount         float64 `json:"amount"`
	Outcome        int32   `json:"outcome"`
	WinAmount      float64 `json:"win_amount"`
	Status         string  `json:"status"`
	IdempotencyKey string  `json:"idempotency_key"`
}

func (q *Queries) CreateBet(ctx context.Context, arg CreateBetParams) (Bet, error) {
	row := q.db.QueryRowContext(ctx, createBet,
		arg.OperatorID,
		arg.PlayerID,
		arg.RoundID,
		arg.Amount,
		arg.Outcome,
		arg.WinAmount,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.RoundID,
		&i.Amount,
		&i.Outcome,
		&i.WinAmount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getBetByIdempotency = `-- name: GetBetByIdempotency :one
SELECT id, operator_id, player_id, round_id, amount, outcome, win_amount, status, idempotency_key, created_at FROM bets
WHERE operator_id = $1 AND idempotency_key = $2
    LIMIT 1
`

type GetBetByIdempotencyParams struct {
	OperatorID     int32  `json:"operator_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetBetByIdempotency(ctx context.Context, arg GetBetByIdempotencyParams) (Bet, error) {
	row := q.db.QueryRowContext(ctx, getBetByIdempotency, arg.OperatorID, arg.IdempotencyKey)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.RoundID,
		&i.Amount,
		&i.Outcome,
		&i.WinAmount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getBetsByRound = `-- name: GetBetsByRound :many
SELECT id, operator_id, player_id, round_id, amount, outcome, win_amount, status, idempotency_key, created_at FROM bets
WHERE round_id = $1
ORDER BY id
`

func (q *Queries) GetBetsByRound(ctx context.Context, roundID int32) ([]Bet, error) {
	rows, err := q.db.QueryContext(ctx, getBetsByRound, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bet
	for rows.Next() {
		var i Bet
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.PlayerID,
			&i.RoundID,
			&i.Amount,
			&i.Outcome,
			&i.WinAmount,
			&i.Status,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBetWin = `-- name: UpdateBetWin :exec
UPDATE bets
SET win_amount = $1, status = $2
WHERE id = $3
`

type UpdateBetWinParams struct {
	WinAmount float64 `json:"win_amount"`
	Status    string  `json:"status"`
	ID        int32   `json:"id"`
}

func (q *Queries) UpdateBetWin(ctx context.Context, arg UpdateBetWinParams) error {
	_, err := q.db.ExecContext(ctx, updateBetWin, arg.WinAmount, arg.Status, arg.ID)
	return err
}
