// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
)

const getOperatorLimits = `-- name: GetOperatorLimits :one
SELECT operator_id, max_bet, allowed_jurisdictions, daily_loss_limit, daily_win_limit
FROM operator_limits
WHERE operator_id = $1
`

func (q *Queries) GetOperatorLimits(ctx context.Context, operatorID int32) (OperatorLimit, error) {
	row := q.db.QueryRowContext(ctx, getOperatorLimits, operatorID)
	var i OperatorLimit
	err := row.Scan(
		&i.OperatorID,
		&i.MaxBet,
		pq.Array(&i.AllowedJurisdictions),
		&i.DailyLossLimit,
		&i.DailyWinLimit,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (operator_id, player_id, action, details)
VALUES (
           $1,
           $2,
           $3,
           $4
       )
`

type InsertAuditLogParams struct {
	OperatorID int32           `json:"operator_id"`
	PlayerID   sql.NullInt32   `json:"player_id"`
	Action     string          `json:"action"`
	Details    json.RawMessage `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.OperatorID,
		arg.PlayerID,
		arg.Action,
		arg.Details,
	)
	return err
}

const upsertOperatorLimits = `-- name: UpsertOperatorLimits :one
INSERT INTO operator_limits (operator_id, max_bet, allowed_jurisdictions, daily_loss_limit, daily_win_limit)
VALUES ($1, $2, $3, $4, $5)
    ON CONFLICT (operator_id)
DO UPDATE SET
    max_bet = EXCLUDED.max_bet,
    allowed_jurisdictions = EXCLUDED.allowed_jurisdictions,
    daily_loss_limit = EXCLUDED.daily_loss_limit,
    daily_win_limit = EXCLUDED.daily_win_limit
    RETURNING operator_id, max_bet, allowed_jurisdictions, daily_loss_limit, daily_win_limit
`

type UpsertOperatorLimitsParams struct {
	OperatorID           int32    `json:"operator_id"`
	MaxBet               float64  `json:"max_bet"`
	AllowedJurisdictions []string `json:"allowed_jurisdictions"`
	DailyLossLimit       float64  `json:"daily_loss_limit"`
	DailyWinLimit        float64  `json:"daily_win_limit"`
}

func (q *Queries) UpsertOperatorLimits(ctx context.Context, arg UpsertOperatorLimitsParams) (OperatorLimit, error) {
	row := q.db.QueryRowContext(ctx, upsertOperatorLimits,
		arg.OperatorID,
		arg.MaxBet,
		pq.Array(arg.AllowedJurisdictions),
		arg.DailyLossLimit,
		arg.DailyWinLimit,
	)
	var i OperatorLimit
	err := row.Scan(
		&i.OperatorID,
		&i.MaxBet,
		pq.Array(&i.AllowedJurisdictions),
		&i.DailyLossLimit,
		&i.DailyWinLimit,
	)
	return i, err
}
