// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID         int32           `json:"id"`
	OperatorID int32           `json:"operator_id"`
	PlayerID   sql.NullInt32   `json:"player_id"`
	Action     string          `json:"action"`
	Details    json.RawMessage `json:"details"`
	CreatedAt  time.Time       `json:"created_at"`
}

type Bet struct {
	ID             int32     `json:"id"`
	OperatorID     int32     `json:"operator_id"`
	PlayerID       int32     `json:"player_id"`
	RoundID        int32     `json:"round_id"`
	Amount         float64   `json:"amount"`
	Outcome        int32     `json:"outcome"`
	WinAmount      float64   `json:"win_amount"`
	Status         string    `json:"status"`
	IdempotencyKey string    `json:"idempotency_key"`
	CreatedAt      time.Time `json:"created_at"`
}

type Operator struct {
	ID            int32     `json:"id"`
	Name          string    `json:"name"`
	ApiKey        string    `json:"api_key"`
	WebhookUrl    string    `json:"webhook_url"`
	WebhookSecret string    `json:"webhook_secret"`
	CreatedAt     time.Time `json:"created_at"`
}

type OperatorLimit struct {
	OperatorID           int32    `json:"operator_id"`
	MaxBet               float64  `json:"max_bet"`
	AllowedJurisdictions []string `json:"allowed_jurisdictions"`
	DailyLossLimit       float64  `json:"daily_loss_limit"`
	DailyWinLimit        float64  `json:"daily_win_limit"`
}

type Outbox struct {
	ID         int32     `json:"id"`
	BetID      int32     `json:"bet_id"`
	OperatorID int32     `json:"operator_id"`
	PlayerID   int32     `json:"player_id"`
	Amount     float64   `json:"amount"`
	CreatedAt  time.Time `json:"created_at"`
	Processed  bool      `json:"processed"`
}

type Player struct {
	ID               int32     `json:"id"`
	OperatorID       int32     `json:"operator_id"`
	ExternalPlayerID string    `json:"external_player_id"`
	Jurisdiction     string    `json:"jurisdiction"`
	CreatedAt        time.Time `json:"created_at"`
}

type Round struct {
	ID         int32     `json:"id"`
	OperatorID int32     `json:"operator_id"`
	PlayerID   int32     `json:"player_id"`
	ServerSeed string    `json:"server_seed"`
	ClientSeed string    `json:"client_seed"`
	Outcome    int32     `json:"outcome"`
	CreatedAt  time.Time `json:"created_at"`
}

type Session struct {
	ID          uuid.UUID `json:"id"`
	OperatorID  int32     `json:"operator_id"`
	PlayerID    int32     `json:"player_id"`
	LaunchToken string    `json:"launch_token"`
	ExpiresAt   time.Time `json:"expires_at"`
	Revoked     bool      `json:"revoked"`
	CreatedAt   time.Time `json:"created_at"`
}

type WebhookEvent struct {
	ID           int32           `json:"id"`
	OperatorID   int32           `json:"operator_id"`
	EventType    string          `json:"event_type"`
	Payload      json.RawMessage `json:"payload"`
	Status       string          `json:"status"`
	Retries      int32           `json:"retries"`
	NextRetryAt  time.Time       `json:"next_retry_at"`
	ErrorMessage sql.NullString  `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}
