// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Operator struct {
	ID        int32
	Name      string
	ApiKey    string
	CreatedAt time.Time
}

type Player struct {
	ID               int32
	OperatorID       int32
	ExternalPlayerID string
	Jurisdiction     string
	CreatedAt        time.Time
}

type Session struct {
	ID          uuid.UUID
	OperatorID  int32
	PlayerID    int32
	LaunchToken string
	ExpiresAt   time.Time
	Revoked     bool
	CreatedAt   time.Time
}
