// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
)

const getPendingOutbox = `-- name: GetPendingOutbox :many
SELECT id, bet_id, operator_id, player_id, amount, created_at, processed
FROM outbox
WHERE processed = FALSE
ORDER BY id
    LIMIT 10
`

func (q *Queries) GetPendingOutbox(ctx context.Context) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutbox)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.OperatorID,
			&i.PlayerID,
			&i.Amount,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutbox = `-- name: InsertOutbox :one
INSERT INTO outbox (bet_id, operator_id, player_id, amount)
VALUES ($1, $2, $3, $4)
    RETURNING id, bet_id, operator_id, player_id, amount, created_at, processed
`

type InsertOutboxParams struct {
	BetID      int32   `json:"bet_id"`
	OperatorID int32   `json:"operator_id"`
	PlayerID   int32   `json:"player_id"`
	Amount     float64 `json:"amount"`
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, insertOutbox,
		arg.BetID,
		arg.OperatorID,
		arg.PlayerID,
		arg.Amount,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.BetID,
		&i.OperatorID,
		&i.PlayerID,
		&i.Amount,
		&i.CreatedAt,
		&i.Processed,
	)
	return i, err
}

const listOutboxByOperator = `-- name: ListOutboxByOperator :many
SELECT id, bet_id, operator_id, player_id, amount, created_at, processed
FROM outbox
WHERE operator_id = $1
ORDER BY id DESC
    LIMIT 200
`

func (q *Queries) ListOutboxByOperator(ctx context.Context, operatorID int32) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxByOperator, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.OperatorID,
			&i.PlayerID,
			&i.Amount,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxByOperatorStatus = `-- name: ListOutboxByOperatorStatus :many
SELECT id, bet_id, operator_id, player_id, amount, created_at, processed
FROM outbox
WHERE operator_id = $1
  AND processed = $2
ORDER BY id DESC
    LIMIT 200
`

type ListOutboxByOperatorStatusParams struct {
	OperatorID int32 `json:"operator_id"`
	Processed  bool  `json:"processed"`
}

func (q *Queries) ListOutboxByOperatorStatus(ctx context.Context, arg ListOutboxByOperatorStatusParams) ([]Outbox, error) {
	rows, err := q.db.QueryContext(ctx, listOutboxByOperatorStatus, arg.OperatorID, arg.Processed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outbox
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.OperatorID,
			&i.PlayerID,
			&i.Amount,
			&i.CreatedAt,
			&i.Processed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :one
UPDATE outbox
SET processed = TRUE
WHERE id = $1
    RETURNING id, bet_id, operator_id, player_id, amount, created_at, processed
`

func (q *Queries) MarkOutboxProcessed(ctx context.Context, id int32) (Outbox, error) {
	row := q.db.QueryRowContext(ctx, markOutboxProcessed, id)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.BetID,
		&i.OperatorID,
		&i.PlayerID,
		&i.Amount,
		&i.CreatedAt,
		&i.Processed,
	)
	return i, err
}
