// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rounds.sql

package sqlc

import (
	"context"
)

const createRound = `-- name: CreateRound :one
INSERT INTO rounds (operator_id, player_id, server_seed, client_seed, outcome)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, operator_id, player_id, server_seed, client_seed, outcome, created_at
`

type CreateRoundParams struct {
	OperatorID int32  `json:"operator_id"`
	PlayerID   int32  `json:"player_id"`
	ServerSeed string `json:"server_seed"`
	ClientSeed string `json:"client_seed"`
	Outcome    int32  `json:"outcome"`
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (Round, error) {
	row := q.db.QueryRowContext(ctx, createRound,
		arg.OperatorID,
		arg.PlayerID,
		arg.ServerSeed,
		arg.ClientSeed,
		arg.Outcome,
	)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.ServerSeed,
		&i.ClientSeed,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}

const getRound = `-- name: GetRound :one
SELECT id, operator_id, player_id, server_seed, client_seed, outcome, created_at FROM rounds
WHERE id = $1
`

func (q *Queries) GetRound(ctx context.Context, id int32) (Round, error) {
	row := q.db.QueryRowContext(ctx, getRound, id)
	var i Round
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.ServerSeed,
		&i.ClientSeed,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}
