// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOperator = `-- name: CreateOperator :one
INSERT INTO operators (name, api_key)
VALUES ($1, $2)
    RETURNING id, name, api_key, webhook_url, webhook_secret, created_at
`

type CreateOperatorParams struct {
	Name   string `json:"name"`
	ApiKey string `json:"api_key"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) (Operator, error) {
	row := q.db.QueryRowContext(ctx, createOperator, arg.Name, arg.ApiKey)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (operator_id, external_player_id, jurisdiction)
VALUES ($1, $2, $3)
    RETURNING id, operator_id, external_player_id, jurisdiction, created_at
`

type CreatePlayerParams struct {
	OperatorID       int32  `json:"operator_id"`
	ExternalPlayerID string `json:"external_player_id"`
	Jurisdiction     string `json:"jurisdiction"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, createPlayer, arg.OperatorID, arg.ExternalPlayerID, arg.Jurisdiction)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalPlayerID,
		&i.Jurisdiction,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, operator_id, player_id, launch_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
    RETURNING id, operator_id, player_id, launch_token, expires_at, revoked, created_at
`

type CreateSessionParams struct {
	ID          uuid.UUID `json:"id"`
	OperatorID  int32     `json:"operator_id"`
	PlayerID    int32     `json:"player_id"`
	LaunchToken string    `json:"launch_token"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.OperatorID,
		arg.PlayerID,
		arg.LaunchToken,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.LaunchToken,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getOperatorByApiKey = `-- name: GetOperatorByApiKey :one
SELECT id, name, api_key, webhook_url, webhook_secret, created_at FROM operators
WHERE api_key = $1
    LIMIT 1
`

func (q *Queries) GetOperatorByApiKey(ctx context.Context, apiKey string) (Operator, error) {
	row := q.db.QueryRowContext(ctx, getOperatorByApiKey, apiKey)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getOperatorByID = `-- name: GetOperatorByID :one
SELECT id, name, api_key, webhook_url, webhook_secret, created_at FROM operators WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOperatorByID(ctx context.Context, id int32) (Operator, error) {
	row := q.db.QueryRowContext(ctx, getOperatorByID, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, operator_id, external_player_id, jurisdiction, created_at FROM players
WHERE operator_id = $1 AND external_player_id = $2
    LIMIT 1
`

type GetPlayerParams struct {
	OperatorID       int32  `json:"operator_id"`
	ExternalPlayerID string `json:"external_player_id"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, arg.OperatorID, arg.ExternalPlayerID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalPlayerID,
		&i.Jurisdiction,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, operator_id, external_player_id, jurisdiction, created_at
FROM players
WHERE id = $1
    LIMIT 1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id int32) (Player, error) {
	row := q.db.QueryRowContext(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalPlayerID,
		&i.Jurisdiction,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, operator_id, player_id, launch_token, expires_at, revoked, created_at FROM sessions
WHERE id = $1
    LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.LaunchToken,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = TRUE
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const verifySessionByToken = `-- name: VerifySessionByToken :one
SELECT id, operator_id, player_id, launch_token, expires_at, revoked, created_at
FROM sessions
WHERE launch_token = $1
  AND operator_id = $2
  AND revoked = FALSE
  AND expires_at > NOW()
    LIMIT 1
`

type VerifySessionByTokenParams struct {
	LaunchToken string `json:"launch_token"`
	OperatorID  int32  `json:"operator_id"`
}

func (q *Queries) VerifySessionByToken(ctx context.Context, arg VerifySessionByTokenParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, verifySessionByToken, arg.LaunchToken, arg.OperatorID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.PlayerID,
		&i.LaunchToken,
		&i.ExpiresAt,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}
